# action.yml
name: 'Update Image Ref'
description: 'Updates in infra repository the reference of the image to be used'
inputs:
  remote)repo_name:  # id of input
    description: 'repo to update'
    required: true
  remote_repo_path:  # id of input
    description: 'file to  update'
    required: true
  remote_repo_branch:
    default: develop
  variable_name:  # id of input
    description: 'which entry to update'
    required: true
  github_user: 
    description: 'github user for the given token'
    required: true # todo get build uers
  github_token:  
    description: 'You probably need a custom token since the automated github tokens won't have rights to push to another repo'
    required: true
  git_commiter_email:
    required: true
  git_commiter_name:
    required: true
  only_if_branch:
    description: 'Don't push unless you're on the specified branch'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
